import { createFileRoute } from "@tanstack/react-router";
import { FormEvent, useEffect, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { api } from "@/lib/api-client";

export const Route = createFileRoute("/_authenticated/business-verification")({ component: BusinessVerificationPage });
function BusinessVerificationPage() {
  const [status, setStatus] = useState<any>({}); const [gstin, setGstin] = useState(""); const [account, setAccount] = useState(""); const [confirm, setConfirm] = useState(""); const [ifsc, setIfsc] = useState(""); const [name, setName] = useState(""); const [message, setMessage] = useState("");
  const load = () => api.getBusinessVerification().then((r) => setStatus(r.data ?? r)).catch((e) => setMessage(e.message)); useEffect(() => { load(); }, []);
  const submitGstin = async (e: FormEvent) => { e.preventDefault(); try { const r = await api.verifyGstin(gstin, name); setStatus(r.data ?? r); setMessage("GSTIN verification submitted."); } catch (e) { setMessage(e instanceof Error ? e.message : "GSTIN verification failed."); } };
  const submitBank = async (e: FormEvent) => { e.preventDefault(); try { const r = await api.verifyBank({ bank_account: account, bank_account_confirmation: confirm, ifsc, name }); setStatus(r.data ?? r); setMessage("Bank verification submitted."); } catch (e) { setMessage(e instanceof Error ? e.message : "Bank verification failed."); } };
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-10"><h1 className="font-display text-3xl font-extrabold">Business verification</h1><p className="mt-2 text-sm text-muted-foreground">GSTIN and bank checks run through the platform verification service. Never enter credentials or upload secrets here.</p>{message && <p className="mt-4 rounded-md border p-3 text-sm">{message}</p>}<div className="mt-8 grid gap-6 md:grid-cols-2"><section className="card-soft p-5"><h2 className="font-display text-lg font-bold">GSTIN</h2><p className="mt-2 text-sm">Status: <b>{status.gstin_status ?? "NOT_STARTED"}</b></p><form onSubmit={submitGstin} className="mt-4 space-y-3"><Input value={gstin} onChange={(e) => setGstin(e.target.value)} placeholder="15-character GSTIN" maxLength={15} required /><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Business name (optional)" /><Button type="submit">Verify GSTIN</Button></form></section><section className="card-soft p-5"><h2 className="font-display text-lg font-bold">Bank account</h2><p className="mt-2 text-sm">Status: <b>{status.bank_verification_status ?? "NOT_STARTED"}</b> · {status.bank_account_masked ?? "No account stored"}</p><form onSubmit={submitBank} className="mt-4 space-y-3"><Input value={account} onChange={(e) => setAccount(e.target.value)} placeholder="Bank account number" required /><Input value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirm bank account number" required /><Input value={ifsc} onChange={(e) => setIfsc(e.target.value)} placeholder="IFSC" maxLength={11} required /><Button type="submit">Verify bank account</Button></form></section></div><div className="mt-6 card-soft p-5"><h2 className="font-display text-lg font-bold">Overall KYB status</h2><p className="mt-2 text-2xl font-extrabold">{status.overall_kyb_status ?? "NOT_STARTED"}</p><p className="mt-2 text-sm text-muted-foreground">Bank account details are displayed only in masked form. If a provider result needs review, the Admin team can record an auditable decision.</p></div></main></div>;
}
