/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as PortalTeamRouteImport } from './routes/portal.team'
import { Route as PortalPerformanceRouteImport } from './routes/portal.performance'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as LotsIdRouteImport } from './routes/lots.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ConsoleVendorsRouteImport } from './routes/console.vendors'
import { Route as ConsoleReportsRouteImport } from './routes/console.reports'
import { Route as ConsoleOrganisationRouteImport } from './routes/console.organisation'
import { Route as ConsoleOrdersRouteImport } from './routes/console.orders'
import { Route as ConsoleFulfilmentRouteImport } from './routes/console.fulfilment'
import { Route as ConsoleFinanceRouteImport } from './routes/console.finance'
import { Route as ConsoleDisputesRouteImport } from './routes/console.disputes'
import { Route as ConsoleAuditRouteImport } from './routes/console.audit'
import { Route as ConsoleApprovalsRouteImport } from './routes/console.approvals'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ConsoleEventsIndexRouteImport } from './routes/console.events.index'
import { Route as PortalEventsIdRouteImport } from './routes/portal.events.$id'
import { Route as ConsoleEventsNewRouteImport } from './routes/console.events.new'
import { Route as ConsoleEventsIdRouteImport } from './routes/console.events.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPerformanceRoute = PortalPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeamRoute = PortalTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const LotsIdRoute = LotsIdRouteImport.update({
  id: '/lots/$id',
  path: '/lots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleVendorsRoute = ConsoleVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReportsRoute = ConsoleReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrganisationRoute = ConsoleOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrdersRoute = ConsoleOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFulfilmentRoute = ConsoleFulfilmentRouteImport.update({
  id: '/fulfilment',
  path: '/fulfilment',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFinanceRoute = ConsoleFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDisputesRoute = ConsoleDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApprovalsRoute = ConsoleApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ConsoleRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConsoleEventsIndexRoute = ConsoleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ConsoleRoute,
} as any)
const PortalEventsIdRoute = PortalEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => PortalRoute,
} as any)
const ConsoleEventsNewRoute = ConsoleEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEventsIdRoute = ConsoleEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/console/approvals': typeof ConsoleApprovalsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/finance': typeof ConsoleFinanceRoute
  '/console/fulfilment': typeof ConsoleFulfilmentRoute
  '/console/orders': typeof ConsoleOrdersRoute
  '/console/organisation': typeof ConsoleOrganisationRoute
  '/console/reports': typeof ConsoleReportsRoute
  '/console/vendors': typeof ConsoleVendorsRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$id': typeof LiveIdRoute
  '/lots/$id': typeof LotsIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/results/$id': typeof ResultsIdRoute
  '/console/': typeof ConsoleIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/console/events/$id': typeof ConsoleEventsIdRoute
  '/console/events/new': typeof ConsoleEventsNewRoute
  '/portal/events/$id': typeof PortalEventsIdRoute
  '/console/events/': typeof ConsoleEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/seller': typeof AuthenticatedSellerRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/console/approvals': typeof ConsoleApprovalsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/finance': typeof ConsoleFinanceRoute
  '/console/fulfilment': typeof ConsoleFulfilmentRoute
  '/console/orders': typeof ConsoleOrdersRoute
  '/console/organisation': typeof ConsoleOrganisationRoute
  '/console/reports': typeof ConsoleReportsRoute
  '/console/vendors': typeof ConsoleVendorsRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$id': typeof LiveIdRoute
  '/lots/$id': typeof LotsIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/results/$id': typeof ResultsIdRoute
  '/console': typeof ConsoleIndexRoute
  '/portal': typeof PortalIndexRoute
  '/console/events/$id': typeof ConsoleEventsIdRoute
  '/console/events/new': typeof ConsoleEventsNewRoute
  '/portal/events/$id': typeof PortalEventsIdRoute
  '/console/events': typeof ConsoleEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/console/approvals': typeof ConsoleApprovalsRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/disputes': typeof ConsoleDisputesRoute
  '/console/finance': typeof ConsoleFinanceRoute
  '/console/fulfilment': typeof ConsoleFulfilmentRoute
  '/console/orders': typeof ConsoleOrdersRoute
  '/console/organisation': typeof ConsoleOrganisationRoute
  '/console/reports': typeof ConsoleReportsRoute
  '/console/vendors': typeof ConsoleVendorsRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$id': typeof LiveIdRoute
  '/lots/$id': typeof LotsIdRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/results/$id': typeof ResultsIdRoute
  '/console/': typeof ConsoleIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/console/events/$id': typeof ConsoleEventsIdRoute
  '/console/events/new': typeof ConsoleEventsNewRoute
  '/portal/events/$id': typeof PortalEventsIdRoute
  '/console/events/': typeof ConsoleEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/portal'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/seller'
    | '/wallet'
    | '/console/approvals'
    | '/console/audit'
    | '/console/disputes'
    | '/console/finance'
    | '/console/fulfilment'
    | '/console/orders'
    | '/console/organisation'
    | '/console/reports'
    | '/console/vendors'
    | '/join/$token'
    | '/live/$id'
    | '/lots/$id'
    | '/portal/documents'
    | '/portal/orders'
    | '/portal/performance'
    | '/results/$id'
    | '/console/'
    | '/portal/'
    | '/console/events/$id'
    | '/console/events/new'
    | '/portal/events/$id'
    | '/console/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/seller'
    | '/wallet'
    | '/console/approvals'
    | '/console/audit'
    | '/console/disputes'
    | '/console/finance'
    | '/console/fulfilment'
    | '/console/orders'
    | '/console/organisation'
    | '/console/reports'
    | '/console/vendors'
    | '/join/$token'
    | '/live/$id'
    | '/lots/$id'
    | '/portal/documents'
    | '/portal/orders'
    | '/portal/performance'
    | '/results/$id'
    | '/console'
    | '/portal'
    | '/console/events/$id'
    | '/console/events/new'
    | '/portal/events/$id'
    | '/console/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/console'
    | '/portal'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/seller'
    | '/_authenticated/wallet'
    | '/console/approvals'
    | '/console/audit'
    | '/console/disputes'
    | '/console/finance'
    | '/console/fulfilment'
    | '/console/orders'
    | '/console/organisation'
    | '/console/reports'
    | '/console/vendors'
    | '/join/$token'
    | '/live/$id'
    | '/lots/$id'
    | '/portal/documents'
    | '/portal/orders'
    | '/portal/performance'
    | '/results/$id'
    | '/console/'
    | '/portal/'
    | '/console/events/$id'
    | '/console/events/new'
    | '/portal/events/$id'
    | '/console/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LiveIdRoute: typeof LiveIdRoute
  LotsIdRoute: typeof LotsIdRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/performance': {
      id: '/portal/performance'
      path: '/performance'
      fullPath: '/portal/performance'
      preLoaderRoute: typeof PortalPerformanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/lots/$id': {
      id: '/lots/$id'
      path: '/lots/$id'
      fullPath: '/lots/$id'
      preLoaderRoute: typeof LotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/vendors': {
      id: '/console/vendors'
      path: '/vendors'
      fullPath: '/console/vendors'
      preLoaderRoute: typeof ConsoleVendorsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/reports': {
      id: '/console/reports'
      path: '/reports'
      fullPath: '/console/reports'
      preLoaderRoute: typeof ConsoleReportsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/organisation': {
      id: '/console/organisation'
      path: '/organisation'
      fullPath: '/console/organisation'
      preLoaderRoute: typeof ConsoleOrganisationRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/orders': {
      id: '/console/orders'
      path: '/orders'
      fullPath: '/console/orders'
      preLoaderRoute: typeof ConsoleOrdersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/fulfilment': {
      id: '/console/fulfilment'
      path: '/fulfilment'
      fullPath: '/console/fulfilment'
      preLoaderRoute: typeof ConsoleFulfilmentRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/finance': {
      id: '/console/finance'
      path: '/finance'
      fullPath: '/console/finance'
      preLoaderRoute: typeof ConsoleFinanceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/disputes': {
      id: '/console/disputes'
      path: '/disputes'
      fullPath: '/console/disputes'
      preLoaderRoute: typeof ConsoleDisputesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/approvals': {
      id: '/console/approvals'
      path: '/approvals'
      fullPath: '/console/approvals'
      preLoaderRoute: typeof ConsoleApprovalsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/console/events/': {
      id: '/console/events/'
      path: '/events'
      fullPath: '/console/events/'
      preLoaderRoute: typeof ConsoleEventsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/portal/events/$id': {
      id: '/portal/events/$id'
      path: '/events/$id'
      fullPath: '/portal/events/$id'
      preLoaderRoute: typeof PortalEventsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/console/events/new': {
      id: '/console/events/new'
      path: '/events/new'
      fullPath: '/console/events/new'
      preLoaderRoute: typeof ConsoleEventsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/events/$id': {
      id: '/console/events/$id'
      path: '/events/$id'
      fullPath: '/console/events/$id'
      preLoaderRoute: typeof ConsoleEventsIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsoleRouteChildren {
  ConsoleApprovalsRoute: typeof ConsoleApprovalsRoute
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleDisputesRoute: typeof ConsoleDisputesRoute
  ConsoleFinanceRoute: typeof ConsoleFinanceRoute
  ConsoleFulfilmentRoute: typeof ConsoleFulfilmentRoute
  ConsoleOrdersRoute: typeof ConsoleOrdersRoute
  ConsoleOrganisationRoute: typeof ConsoleOrganisationRoute
  ConsoleReportsRoute: typeof ConsoleReportsRoute
  ConsoleVendorsRoute: typeof ConsoleVendorsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleEventsIdRoute: typeof ConsoleEventsIdRoute
  ConsoleEventsNewRoute: typeof ConsoleEventsNewRoute
  ConsoleEventsIndexRoute: typeof ConsoleEventsIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleApprovalsRoute: ConsoleApprovalsRoute,
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleDisputesRoute: ConsoleDisputesRoute,
  ConsoleFinanceRoute: ConsoleFinanceRoute,
  ConsoleFulfilmentRoute: ConsoleFulfilmentRoute,
  ConsoleOrdersRoute: ConsoleOrdersRoute,
  ConsoleOrganisationRoute: ConsoleOrganisationRoute,
  ConsoleReportsRoute: ConsoleReportsRoute,
  ConsoleVendorsRoute: ConsoleVendorsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleEventsIdRoute: ConsoleEventsIdRoute,
  ConsoleEventsNewRoute: ConsoleEventsNewRoute,
  ConsoleEventsIndexRoute: ConsoleEventsIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface PortalRouteChildren {
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalTeamRoute: typeof PortalTeamRoute
  PortalPerformanceRoute: typeof PortalPerformanceRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalEventsIdRoute: typeof PortalEventsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalTeamRoute: PortalTeamRoute,
  PortalPerformanceRoute: PortalPerformanceRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalEventsIdRoute: PortalEventsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  JoinTokenRoute: JoinTokenRoute,
  LiveIdRoute: LiveIdRoute,
  LotsIdRoute: LotsIdRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
